### ISSUE TITLE
Error message: code 400

### ISSUE THREAD

**Issue by LishuZh** [robertdkirkby/getfreddata-matlab#3]
Hi,

I tried to download data with getFredData and this Error message kept coming up:

Error using xmlread (line 116)
Java exception occurred:
java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.stlouisfed.org/fred/series/observations?series_id=GDPC1&observation_start=1947-01-01&observation_end=2022-03-31&units=q&api_key=f2d19173c3fe83dba3461c85f30ac38a

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)

	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)

	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)

	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)

	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)

	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)

	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)

	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)

Error in getFredData (line 146)
xDoc2=xmlread(['https://api.stlouisfed.org/fred/series/observations?series_id=',series_id,optionstring,'&api_key=',api_key]);

I have read the previous thread and tried to add pauses. But obviously my error code is different and it didn't solve the problem. Besides, I tried to use different item codes for the Real GDP. The code I am using in this trial was drawn from the given example. I wonder if anyone can give a hint on what went wrong and how I can possibly solve it. Thank you in advance!

**Comment by LishuZh** [comment]
Fixed it by deleting 'q'. The data are formatted as quarterly as they are.
